Task: reward
OutputDir : outputs/reward
Seed : 42

ModelConfig : 
  model_path : models/gpt2-reward

DatasetConfig :
  dataset_path : datasets/emotion-reward

TrainerConfig :
  eval_steps : 30
  save_steps : 60  
  per_device_train_batch_size : 32
  per_device_eval_batch_size : 64
  num_train_epochs : 5
  learning_rate : 5.0e-5
  weight_decay : 0.01
